---
- name: Configure Treetracker App Instance
  hosts: all
  gather_facts: false
  become: true

  pre_tasks:
    - name: Install python for Ansible to work
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: false

## Todo here: all the steps in the configuration.sh script in order to prebake
#  a packer image.
  tasks:
    - name: initial dist upgrade
      apt:
        upgrade: dist
        update_cache: yes
        cache_valid_time: 3600

    - name: Set up users
      include_role:
        name: users
    - name: Harden SSH config
      include_role:
        name: ssh
    - name: Install Nginx
      include_role:
        name: nginx
    - name: Install NodeJS
      include_role:
        name: nodejs
    - name: Install Postgres
      include_role:
        name: postgres
